[build]
  publish = "dist"
  command = "npm run build"

# Переменные окружения для сборки
[build.environment]
  VITE_DEV_MODE = "true"

# Редиректы для API
[[redirects]]
  from = "/api/*"
  to = "https://di.slovo-soft.ru:6443/:splat"
  status = 200
  force = true
  
# Редирект для SPA
[[redirects]]
  from = "/*"
  to = "/test/backend_integration"
  status = 200

# Заголовки для всех запросов
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Заголовки для API запросов
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-TOKEN, X-Front-Token" 