[build]
  publish = "dist"
  command = "npm run build"

# Переменные окружения для сборки
[build.environment]
  VITE_DEV_MODE = "true"

# Специальный редирект для виджета чата
[[redirects]]
  from = "/api/widget-proxy"
  to = "https://knowledge.slovo-soft.ru/api/v1/mentorium"
  status = 200
  force = true
  
# Общий редирект для API (для обратной совместимости)
[[redirects]]
  from = "/api/*"
  to = "https://knowledge.slovo-soft.ru/:splat"
  status = 200
  force = true
  
# Редирект для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Country = ["*"]}

# Заголовки для всех запросов
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "frame-ancestors 'self' *.netlify.app"

# Специальные заголовки для прокси виджета
[[headers]]
  for = "/api/widget-proxy"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Target-URL, X-TOKEN, X-Front-Token"
    Access-Control-Max-Age = "86400"

# Заголовки для API запросов
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-TOKEN, X-Front-Token"

[[redirects]]
  from = "/test/*"
  to = "/test/backend_integration"
  status = 301
  force = false

[[redirects]]
  from = "/"
  to = "/widget/example.html"
  status = 301
  force = false 